### PR TITLE
Take DOCKER_TLS_VERIFY env variable into account

### PR DESCRIPTION
**Pull request by ierceg**
Display the actual Docker connection exception for easier troubleshooting

### CODE REVIEW

**Comment by stevenjack** [comment]
@ierceg Thanks for doing this, I'd been meaning to get around to it!

**Comment by ierceg** [comment]
@stevenjack Thank you for spurious!

**Comment by ierceg** [comment]
@stevenjack when do you think the `gem` repository version will be updated?

**Comment by Integralist** [comment]
@ierceg Saw your last comment and thought i would quickly say that Steve is on holiday at the moment. So in case you don't hear anything back in the next few days, it'll be because he has no internet access.

**Comment by stevenjack** [comment]
Hey @ierceg I released the latest version yesterday after merging your fix!  Out of interest how did you find spurious?

**Comment by ierceg** [comment]
@Integralist thanks for jumping in.

@stevenjack Thanks - appreciate the quick turnaround! Re how I found out about spurious, I think I just googled for "fake s3 docker" or something such.

**Pull request closed without merging**
